import { DarkTheme, LightTheme } from "styled-components";

export const lightTheme: LightTheme = {
  mainBlue: "#2da0fa",
  mainWhite: "#ffffff",
  mainBlack: "#191F28",
  mainGray: "#B0B8C1",
  mainText: "#191F28",
  mainBlueHover: "#0d6efd",
  border: "#e1e1e1",
  mainBackground: "#ffffff",
  footerBackground: "#f2f2f2",
  navBackground: "#ffffff",
  dashboardBackground: "#2da0fa",
  dashboardMenuBackground: "#acdbff",
  modalBackground: "#fafafa5f",
  modalContentBackground: "#ffffff9d",
  functionArrowWhite: "#fff",
};
export const darkTheme: DarkTheme = {
  mainBlue: " #0d92ff",
  mainWhite: "#2b2b2b",
  mainBlack: "#2b2b2b",
  mainGray: "#676767",
  mainText: "#ffffff",
  mainBlueHover: "#0066ff",
  border: "#515151",
  mainBackground: "#171717",
  footerBackground: "#202020",
  navBackground: "#202020",
  dashboardBackground: "#151515",
  dashboardMenuBackground: "#151515",
  modalBackground: "#44444440",
  modalContentBackground: "#60606070",
  functionArrowWhite: "#fff",
};
